# The Chain Rule...
# finding the derivative of z with respect to x...
from sympy import *

# declear x to sympy...
x = symbols('x ')

# define function...
z = (x ** 2 + 1) ** 3 - 2

# making object...
dz_dx = diff(z, x)

# print dz_dx...
print(dz_dx)

# calculating the derivative dz/dx wth, but still getting the same answer...

from sympy import * 
 
# declar x and y to sympy... 
x, y = symbols('x y')

# derivative for first function... 
# need to underscore y to prevent variable clash... 
_y = x ** 2 + 1
dy_dx = diff(_y)

# derivative for second function...
z = y ** 3 - 2
dz_dy = diff(z)

# calculate derivative with and without... 
# apply chain rule, substitute y function... 
dz_dx_chain = (dy_dx * dz_dy).subs(y, _y)
dz_dx_no_chain = diff(z. subs(y, _y))

# prove chain rule by showing both are equal... 
print(dz_dx_chain)
print(dz_dx_no_chain)